name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install -e .
    - name: test ${{ matrix.os }} - ${{ matrix-python-version }}
      run: |
        pytest
